server:
  port: 8085


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/category/**
        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/client/**
        - id: ms-produto-service
          uri: lb://ms-produto-service
          predicates:
            - Path=/produt/**
        - id: ms-pedido-service
          uri: lb://ms-pedido-service
          predicates:
            - Path=/order/**
